### ISSUE TITLE
windows only?

### ISSUE THREAD

**Issue by mattvenn** [rmawatson/PyEagle#1]
I tried setting this up under Linux but it seems only .exe files are available for the eagle launcher?
Any tips on how to go about getting this working with Linux?

**Comment by rmawatson** [comment]
Eagle launcher could be rewritten in about 2 minutes in python, it literally just launches python with the given script, then returns. This is so that the system() command in eagle returns straight away. and the script is running as a separate 'disconnected' process. If it were to directly launch python with the script, the whole thing would deadlock, as the system relies on eagle returning and rerunning the script again and again for communication.

The rest should work on windows or linux.. its just python.

The original intention was that the launcher might do other things, such as inject a dll into the eagle process so I could then sublcass any of the controls and insert my own menus etc.. I never needed to do this however.

Cheers

Rob.

**Comment by mattvenn** [comment]
Rob, ok I'll try it!

On 28 July 2014 15:37, rmawatson notifications@github.com wrote:

> Eagle launcher could be rewritten in about 2 minutes in python, it
> literally just launches python with the given script, then returns. This is
> so that the system() command in eagle returns straight away. and the script
> is running as a separate process. If it were to directly launch python with
> the script, the whole thing would deadlock, as the system relies on eagle
> returning and rerunning the script again and again for communication.
> 
> The rest should work on windows or linux.. its just python.
> 
> The original intention was that the launcher might do other things, such
> as inject a dll into the eagle process so I could then sublcass any of the
> controls and insert my own menus etc.. I never needed to do this however.
> 
> Cheers
> 
> Rob.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rmawatson/PyEagle/issues/1#issuecomment-50346658.

## 

Matthew Venn
mattvenn.net

**Comment by EagleScripting** [comment]
How about something like this:

``` python
import sys

if len(sys.argv) != 2:
  print "Please specify which command to run"
  sys.exit()

subproc = sys.argv[1]

from subprocess import Popen

pid = Popen(["python", subproc], close_fds=True).pid

if pid:
  print "Process ID: ", pid
```

GIST: <a href="https://gist.github.com/EagleScripting/9b89eb3cfdcc82b8638e#file-launcher-py">launcher.py</a>

**Comment by mattvenn** [comment]
OK, I tried that, set the paths up though don't know what eagle_python_path should point to. I've got it set to the top level directory with the .py scripts in.

When I run this on the eagle command line

RUN eagle_python_dispatcher.ulp alignment_tool.py

I get an error box with the below inside. Line 39 looks fine to me, though I'm not familiar with the ulp format.

/home/mattvenn/work/eagle-circuit-designs/PyEagle/ulp/ULTextHandler.ulp(39):

syntax error

Included by:
/home/mattvenn/work/eagle-circuit-designs/PyEagle/ulp/eagle_python_dispatcher.ulp(18)
/home/mattvenn/work/eagle-circuit-designs/PyEagle/ulp/ULBaseHandler.ulp(21)
/home/mattvenn/work/eagle-circuit-designs/PyEagle/ulp/ULBoardHandler.ulp(23)
/home/mattvenn/work/eagle-circuit-designs/PyEagle/ulp/ULAttributeHandler.ulp(21)

**Comment by rmawatson** [comment]
I think its one of the lines above. I commit a fix I think for this issue... it was a missing semicolon the previous line.
Does that fix it>?

Date: Tue, 5 Aug 2014 08:13:53 -0700

**Comment by mattvenn** [comment]
I tried a pull and was already up to date. Which file did you fix? I had a look at line 39 again and semicolons look fine to me.

**Comment by rmawatson** [comment]
Also, EAGLE_PYTHON_PATH is where it searches for any python scripts you want to run. If you look below in the script how it is used it should make sense.

Checking if the "xxx.py" script exists..
    if (filetime(EAGLE_PYTHON_PATH + argv[1]) == 0) {       dlgMessageBox("Script '" + argv[1] + "' does not exist in " + EAGLE_PYTHON_PATH);       exit(1);    }
Running the launcher, with the scripts full path.
system(EAGLE_LAUNCHER_PATH + " \"" + PYTHON_EXECUTABLE + " " + EAGLE_PYTHON_PATH +  argv[1] + arguments +"\" ");

etc..
What version of eagle are you using ?
Date: Tue, 5 Aug 2014 08:13:53 -0700

**Comment by mattvenn** [comment]
OK, I think the path is right then. 
This is line 39: cacheResult += intToStr(Text.align) + "?";
And I'm on 5.12.0
Thanks for the help by the way!

**Comment by rmawatson** [comment]
yea, must not be the same problem.. Works for me with 6.60

Date: Tue, 5 Aug 2014 08:18:17 -0700

**Comment by rmawatson** [comment]
I didn't ever try it on < version 6. it may be that Text.align does not exist, you can try commenting that line out.

Date: Tue, 5 Aug 2014 08:20:57 -0700

**Comment by rmawatson** [comment]
Best way to check actually is look in the help under "User Language -> Object Types". If you have UL_TEXT, check if it has those properties
this is how it looks for me..
UL_TEXT
Data members 

align 

int (ALIGN_...)

angle 

real (0.0...359.9)

font 

int (FONT_...)

layer 

int

linedistance 

int

mirror 

int

ratio 

int

size 

int

spin 

int

value 

string

x, y 

int (origin point)

Loop members 

wires() 

UL_WIRE (see note)

See also UL_BOARD, UL_PACKAGE, UL_SHEET, UL_SYMBOL 

Constants

FONT_VECTOR 

vector font

FONT_PROPORTIONAL 

proportional font

FONT_FIXED 

fixed font

ALIGN_BOTTOM_LEFT 

bottom/left aligned

ALIGN_BOTTOM_CENTER 

bottom/center aligned

ALIGN_BOTTOM_RIGHT 

bottom/right aligned

ALIGN_CENTER_LEFT 

center/left aligned

ALIGN_CENTER 

centered

ALIGN_CENTER_RIGHT 

center/right aligned

ALIGN_TOP_LEFT 

top/left aligned

ALIGN_TOP_CENTER 

top/center aligned

ALIGN_TOP_RIGHT 

top/right aligned

Note
The wires() loop member always accesses the individual wires the text is composed of when using the vector font, even if the actual font is not FONT_VECTOR. 

If the UL_TEXT is derived from a UL_ELEMENT or UL_INSTANCE context, the member values will be those of the actual text as located in the board or sheet drawing. 
Example
board(B) {
  B.texts(T) {
    printf("Text: %s\n", T.value);
    }
  } 
Date: Tue, 5 Aug 2014 08:20:57 -0700

**Comment by mattvenn** [comment]
OK, commented that and another align out and got the next error, line 24 on
ULDimensionHandler, which looks like a function def:
string ULDimensionHandler(UL_DIMENSION Dimension,string currentPath, string
argument, char cacheMode)

So probably this isn't going to work on eagle 5. Boo hoo.

On 5 August 2014 16:24, rmawatson notifications@github.com wrote:

> I didn't ever try it on < version 6. it may be that Text.align does not
> exist, you can try commenting that line out.
> 
> Date: Tue, 5 Aug 2014 08:20:57 -0700
> From: notifications@github.com
> To: PyEagle@noreply.github.com
> CC: rmawatson@hotmail.com
> Subject: Re: [PyEagle] windows only? (#1)
> 
> OK, I think the path is right then.
> 
> This is line 39: cacheResult += intToStr(Text.align) + "?";
> 
> And I'm on 5.12.0
> 
> Thanks for the help by the way!
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rmawatson/PyEagle/issues/1#issuecomment-51213221.

## 

Matthew Venn
mattvenn.net

**Comment by rmawatson** [comment]
I would expect it would work fine on 5.50. But you might have to do some work first. You just need to comment out some blocks. This whole thing was wrapped by a script that generated those ULP's, So some of the stuff might not work properly/as expected anyway. For this one, look for UL_DIMENSION in the 'Object Types' If it doesn't exist ,comment that block out. 
Ideally you would want to comment the matching parts out in the python stuff, but if you don't use them, it won't break..

Date: Tue, 5 Aug 2014 08:27:37 -0700

**Comment by mattvenn** [comment]
OK, I'll have a go. Can you tell me how to get the object types and
parameters? I couldn't find that menu you mentioned.

On 5 August 2014 16:31, rmawatson notifications@github.com wrote:

> I would expect it would work fine on 5.50. But you might have to do some
> work first. You just need to comment out some blocks. This whole thing was
> wrapped by a script that generated those ULP's, So some of the stuff might
> not work properly/as expected anyway. For this one, look for UL_DIMENSION
> in the 'Object Types' If it doesn't exist ,comment that block out.
> Ideally you would want to comment the matching parts out in the python
> stuff, but if you don't use them, it won't break..
> 
> Date: Tue, 5 Aug 2014 08:27:37 -0700
> From: notifications@github.com
> To: PyEagle@noreply.github.com
> CC: rmawatson@hotmail.com
> Subject: Re: [PyEagle] windows only? (#1)
> 
> OK, commented that and another align out and got the next error, line 24 on
> 
> ULDimensionHandler, which looks like a function def:
> 
> string ULDimensionHandler(UL_DIMENSION Dimension,string currentPath, string
> 
> argument, char cacheMode)
> 
> So probably this isn't going to work on eagle 5. Boo hoo.
> 
> On 5 August 2014 16:24, rmawatson notifications@github.com wrote:
> 
> > I didn't ever try it on < version 6. it may be that Text.align does not
> > 
> > exist, you can try commenting that line out.
> > 
> > Date: Tue, 5 Aug 2014 08:20:57 -0700
> > 
> > From: notifications@github.com
> > 
> > To: PyEagle@noreply.github.com
> > 
> > CC: rmawatson@hotmail.com
> > 
> > Subject: Re: [PyEagle] windows only? (#1)
> > 
> > OK, I think the path is right then.
> > 
> > This is line 39: cacheResult += intToStr(Text.align) + "?";
> > 
> > And I'm on 5.12.0
> > 
> > Thanks for the help by the way!
> > 
> > —
> > 
> > Reply to this email directly or view it on GitHub.
> > 
> > —
> > 
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/rmawatson/PyEagle/issues/1#issuecomment-51213221.
> 
> ## 
> 
> Matthew Venn
> 
> mattvenn.net
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rmawatson/PyEagle/issues/1#issuecomment-51214351.

## 

Matthew Venn
mattvenn.net

**Comment by rmawatson** [comment]
Should be in the help file. For me it was under Help -> General -> User Language -> Object Types

Date: Tue, 5 Aug 2014 11:20:25 -0700
